name: Java CI with Maven
on:
  pull_request:
    branches: [ "dev-test" ]
jobs:
  check-maven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Print greeting
      run: echo "Hello, World!"
    - name: Print greeting
      run: echo "Hello, World45"